apiVersion: v1
kind: ConfigMap
metadata:
  name: ops-assistant-config
  namespace: ops-assistant
data:
  LLM_PROVIDER: bedrock
  AWS_REGION: us-east-1
  BEDROCK_MODEL: us.amazon.nova-2-lite-v1:0
  PROMETHEUS_URL: http://ops-monitor-kube-prometheu-prometheus.monitoring.svc.cluster.local:9090
  CORS_ORIGINS: ""
